name: soundscape
channels:
  - pytorch
  - prometeia
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - bzip2=1.0.8=h99b78c6_7
  - ca-certificates=2022.6.15=h4653dfc_0
  - gmp=6.3.0=h7bae524_2
  - gmpy2=2.1.5=py310heb17c8b_2
  - libblas=3.9.0=16_osxarm64_openblas
  - libcblas=3.9.0=16_osxarm64_openblas
  - libcxx=19.1.4=ha82da77_0
  - libffi=3.4.2=h3422bc3_5
  - libgfortran=5.0.0=13_2_0_hd922786_3
  - libgfortran5=13.2.0=hf226fd6_3
  - liblapack=3.9.0=16_osxarm64_openblas
  - libopenblas=0.3.21=openmp_hc731615_3
  - libsqlite=3.39.4=h76d750c_0
  - libzlib=1.2.12=ha287fd2_2
  - llvm-openmp=14.0.4=hd125106_0
  - mpc=1.3.1=h8f1351a_1
  - mpfr=4.2.1=hb693164_3
  - mpmath=1.3.0=pyhd8ed1ab_0
  - ncurses=6.3=h07bb92c_1
  - networkx=3.4.2=pyh267e887_2
  - openblas=0.3.21=openmp_hf78f355_3
  - openssl=3.4.0=h39f12f2_0
  - python=3.10.6=hae75cb6_0_cpython
  - python_abi=3.10=5_cp310
  - readline=8.1.2=h46ed386_0
  - setuptools=75.6.0=pyhff2d567_1
  - six=1.16.0=pyh6c4a22f_0
  - tk=8.6.12=he1e0b03_0
  - typing_extensions=4.12.2=pyha770c72_0
  - xz=5.2.6=h57fd34a_0
  - pip:
      - accelerate==1.1.1
      - aiohappyeyeballs==2.4.3
      - aiohttp==3.11.8
      - aiosignal==1.3.1
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - asteroid-filterbanks==0.4.0
      - async-timeout==5.0.1
      - attrs==24.2.0
      - audioread==3.0.1
      - bella==2.1.6
      - blinker==1.9.0
      - build==1.2.2.post1
      - certifi==2024.8.30
      - cffi==1.17.1
      - charset-normalizer==3.4.0
      - ci-sdr==0.0.2
      - click==8.1.7
      - cloudpickle==3.1.0
      - configargparse==1.7
      - ctc-segmentation==1.7.4
      - cython==3.0.11
      - dataclasses-json==0.5.14
      - datasets==3.1.0
      - decorator==5.1.1
      - demucs==4.1.0a2
      - dill==0.3.8
      - distance==0.1.3
      - dora-search==0.1.12
      - editdistance==0.8.1
      - einops==0.8.0
      - enum34==1.1.10
      - espnet==202402
      - espnet-tts-frontend==0.0.3
      - evaluate==0.4.3
      - fast-bss-eval==0.1.3
      - ffmpeg-python==0.2.0
      - filelock==3.16.1
      - fire==0.3.1
      - flask==3.1.0
      - frozenlist==1.5.0
      - fsspec==2024.10.0
      - future==1.0.0
      - g2p-en==2.1.0
      - h5py==3.12.1
      - huggingface-hub==0.26.3
      - humanfriendly==10.0
      - hydra-core==1.3.2
      - hyperpyyaml==1.2.2
      - idna==3.10
      - importlib-metadata==4.13.0
      - inflect==7.0.0
      - isodate==0.6.1
      - itsdangerous==2.2.0
      - jaconv==0.4.0
      - jamo==0.4.1
      - jinja2==3.1.4
      - joblib==1.4.2
      - julius==0.2.7
      - kaldiio==2.18.0
      - lameenc==1.7.0
      - lazy-loader==0.4
      - librosa==0.9.2
      - llvmlite==0.43.0
      - markupsafe==3.0.2
      - marshmallow==3.23.1
      - more-itertools==10.5.0
      - msgpack==1.1.0
      - multidict==6.1.0
      - multiprocess==0.70.16
      - mypy-extensions==1.0.0
      - nltk==3.9.1
      - numba==0.60.0
      - numpy==1.26.4
      - oauthlib==3.2.2
      - omegaconf==2.3.0
      - openai-whisper==20230124
      - openunmix==1.3.0
      - opt-einsum==3.4.0
      - packaging==24.2
      - pandas
      - pillow==11.0.0
      - pip==24.3.1
      - platformdirs==4.3.6
      - pooch==1.8.2
      - propcache==0.2.0
      - protobuf==3.20.3
      - psutil==6.1.0
      - pyarrow==18.1.0
      - pycparser==2.22
      - pydantic==2.10.3
      - pydantic-core==2.27.1
      - pydub==0.25.1
      - pypinyin==0.44.0
      - pyproject-hooks==1.2.0
      - python-dateutil==2.9.0.post0
      - python-youtube==0.6.4
      - pytube3==9.6.4
      - pytz==2024.2
      - pyworld==0.3.4
      - pyyaml==6.0.2
      - regex==2024.11.6
      - requests==2.32.3
      - requests-oauthlib==1.3.1
      - resampy==0.4.3
      - retrying==1.3.4
      - ruamel-yaml==0.18.6
      - ruamel-yaml-clib==0.2.12
      - s3prl==0.4.16
      - safetensors==0.4.5
      - scikit-learn==1.5.2
      - scipy==1.14.1
      - sentencepiece==0.1.97
      - soundfile==0.12.1
      - soxr==0.5.0.post1
      - speechbrain==1.0.2
      - submitit==1.5.2
      - sympy==1.13.1
      - tabulate==0.9.0
      - termcolor==2.5.0
      - threadpoolctl==3.5.0
      - tokenizers==0.20.3
      - tomli==2.2.1
      - torch==2.5.1
      - torch-complex==0.4.4
      - torchaudio==2.5.1
      - torchvision==0.20.1
      - tqdm==4.67.1
      - transformers==4.46.3
      - treetable==0.2.5
      - typeguard==2.13.3
      - typing-inspect==0.9.0
      - tzdata==2024.2
      - ujson==5.10.0
      - unidecode==1.3.8
      - urllib3==2.2.3
      - werkzeug==3.1.3
      - wheel==0.45.1
      - xxhash==3.5.0
      - yarl==1.18.0
      - yt-dlp==2024.11.18
      - zipp==3.21.0
variables:
  PIP_REQUIRE_VIRTUALENV: 'false'
